"""
Generates a downloadable PDF of the AI executive report, so it's something
a business owner can actually save, print, or forward — not just text
trapped on a dashboard.
"""
from fpdf import FPDF
from datetime import datetime, timezone
import io


def generate_report_pdf(report_text: str, generated_with: str = "AI") -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "SOC 2 Security Posture Report", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pdf.cell(0, 6, f"Generated {timestamp} ({generated_with})", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 11)

    # fpdf2's multi_cell handles wrapping; encode defensively since the
    # AI-generated text may contain characters outside Helvetica's base
    # font support (smart quotes, em dashes, etc.).
    safe_text = report_text.encode("latin-1", "replace").decode("latin-1")
    for paragraph in safe_text.split("\n"):
        if paragraph.strip():
            pdf.multi_cell(0, 7, paragraph)
            pdf.ln(3)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.ln(5)
    pdf.multi_cell(
        0, 5,
        "Generated by the SOC 2 Evidence Collector (open source). This report "
        "summarizes automated findings and does not constitute a formal SOC 2 "
        "audit or attestation."
    )

    output = pdf.output()
    return bytes(output)
